version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: unless-stopped
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
