---
- name: Setup Log Backup System
  hosts: target_servers
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: 
          - gzip
          - cron
        state: present
        update_cache: yes
      
    - name: Copy backup script
      copy:
        src: backup_logs.sh
        dest: /usr/local/bin/backup_logs.sh
        mode: '0755'
        owner: root
        group: root
      
    - name: Setup cron job for hourly backups
      cron:
        name: "Hourly log backup"
        minute: "0"
        hour: "*"
        job: "/usr/local/bin/backup_logs.sh > /var/log/backup_cron.log 2>&1"
        state: present
